In [1]:
import pandas as pd
import os as os
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
import matplotlib
import statistics 

# Plotting libraries
import matplotlib.pyplot as plt
import seaborn as sns


import statistics

import re
import pandas as pd
import numpy as np
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from string import punctuation

# Model Building

1. Logistic Regression
2. Convolution Neural Networks(CNN)
3. Long Short term Memory Networks(LSTM)

Among three Logistic Regression showed better results of Accuracy on validation data

1.Logistic Regression:

Results are as follows:

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.2min

[Parallel(n_jobs=-1)]: Done  70 out of  70 | elapsed:  1.7min finished

Validation Accuracy: 0.6883942766295708

2.Convolution Neural Networks(CNN):
epochs : 5

Time taken:3.2 mins

Validation Accuracy: 0.6455

3.LSTM:
epochs: 6

Time taken:2.4 mins

Validation Accuracy: 0.6383

Cross Validation:

Performed cross validation using GridSearchCV on Logistic Regression
1. using array of values of 'C' (smaller the values of C better are the results), 
C = 10 showed a good improvement in model, further increase in C reduced the accuracy.

2. class_weight as Balanced

3. used tolerance which gave a signifinantly low accuracy so took a single value of 0.01 (tol: max value = 0.0001)

In [2]:
os.chdir("C:/PHD")
%run Library_list.ipynb

In [3]:
trainData = pd.read_csv("Train-1554810061973.csv",encoding='latin-1')
print(trainData.shape) # Print the dimensions of train DataFrame
print(trainData.columns) # Print the column names of the DataFrame
print('\n')
trainData.head(5)

(6287, 6)
Index(['Reviewid', 'Hotelid', 'userid', 'Date', 'reviewtext', 'Sentiment'], dtype='object')




Reviewid    Hotelid      userid       Date  \
0  Review_1  hotel_101  hotel_1608  16-Nov-07   
1  Review_2  hotel_101  hotel_6939  30-Oct-07   
2  Review_3  hotel_101  hotel_3976  12-Oct-07   
3  Review_4  hotel_101  hotel_2851  31-Aug-07   
4  Review_5  hotel_101  hotel_7897  18-Jul-07   

                                          reviewtext Sentiment  
0        Nice Marriot       View of my king bed room      good  
1  Good hotel, charges for internet access The Ma...      good  
2  Small but adequate rooms If you have an early ...      good  
3  Better than average, some noisy rooms I have s...      good  
4  Ordinary Although it is highly rated in these ...       bad

In [4]:
testData = pd.read_csv("Test-1555730055539.csv",encoding='latin-1')
print(testData.shape) # Print the dimensions of train DataFrame
print(testData.columns) # Print the column names of the DataFrame
print('\n')
testData.head(5)

(3468, 5)
Index(['Reviewid', 'Hotelid', 'userid', 'Date', 'reviewtext'], dtype='object')




Reviewid    Hotelid      userid          Date  \
0  Review_11001  hotel_101  hotel_2225  Dec 13, 2008   
1  Review_11002  hotel_101  hotel_5079   Dec 2, 2008   
2  Review_11003  hotel_101  hotel_8440  Nov 18, 2008   
3  Review_11004  hotel_101  hotel_4592  Oct 19, 2008   
4  Review_11005  hotel_101  hotel_5901  Oct 13, 2008   

                                          reviewtext  
0  Just An Average stay This was just an average ...  
1  go elsewhere The place is hugely overpriced an...  
2  I Won't Go Back I stayed at the hotel 11/14/08...  
3  Good weekend stay My wife and I stay here quit...  
4  Great airport stay Lovely indoor pool area, lo...

In [5]:
reviewId = trainData['Reviewid']
reviewId_Test = testData['Reviewid']

In [6]:
trainData.head(10)

Reviewid    Hotelid      userid       Date  \
0   Review_1  hotel_101  hotel_1608  16-Nov-07   
1   Review_2  hotel_101  hotel_6939  30-Oct-07   
2   Review_3  hotel_101  hotel_3976  12-Oct-07   
3   Review_4  hotel_101  hotel_2851  31-Aug-07   
4   Review_5  hotel_101  hotel_7897  18-Jul-07   
5   Review_6  hotel_101  hotel_3297  13-Jul-07   
6   Review_7  hotel_101  hotel_5463   4-Jul-07   
7   Review_8  hotel_101  hotel_9766  14-Jun-07   
8   Review_9  hotel_101  hotel_7042  13-Jun-07   
9  Review_10  hotel_101  hotel_9805  30-May-07   

                                          reviewtext  Sentiment  
0        Nice Marriot       View of my king bed room       good  
1  Good hotel, charges for internet access The Ma...       good  
2  Small but adequate rooms If you have an early ...       good  
3  Better than average, some noisy rooms I have s...       good  
4  Ordinary Although it is highly rated in these ...        bad  
5  Awesome for early AM flight Wow! what a supris...  excellent  
6  Good Stay Spent two nights there in Jun. The h...       good  
7  Great Staff We stayed overnight the last week ...  excellent  
8  fine choice for seatac The lobby is attractive...       good  
9  Great value, looking for a nice hotel. not exp...       good

In [7]:
import nltk
from nltk.tokenize import word_tokenize

In [8]:
reviews =trainData.reviewtext.str.cat(sep=' ')

In [9]:
reviews_test = testData.reviewtext.str.cat(sep=' ')

In [10]:
tokens = word_tokenize(reviews)

In [11]:
tokens_test = word_tokenize(reviews_test)

In [12]:
vocabulary = set(tokens)
print(len(vocabulary))

36289


In [13]:
vocabulary_test = set(tokens_test)
print(len(vocabulary_test))

24936


In [394]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
tokens = [w for w in tokens if not w in stop_words]

In [434]:
stop_words_test = set(stopwords.words('english'))
tokens_test_1 = [w for w in tokens_test if not w in stop_words_test]

In [14]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

C:\Users\CBPLDEV11\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [20]:
max_num_words = 200 # setting input shape
seq_len = 200
embedding_size = 100

data=trainData.loc[:,["reviewtext","Sentiment"]]

In [16]:
from nltk import sent_tokenize

from googletrans import Translator
translator = Translator()


In [21]:
## Custom function for Text clean up.

from nltk.tokenize import WhitespaceTokenizer
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag

from nltk.corpus import wordnet

def get_wordnet_pos(pos_tag):
    if pos_tag.startswith('J'):
        return wordnet.ADJ
    elif pos_tag.startswith('V'):
        return wordnet.VERB
    elif pos_tag.startswith('N'):
        return wordnet.NOUN
    elif pos_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

def clean_text(text): #clean text
    # #     text = text.translate()
    text=text.lower()
    text = re.sub(r"what's", "what is ", text)
    text = re.sub(r"what'd", "what would ", text)
    text = re.sub(r"\'ve", " have ", text)
    text = re.sub(r"n't", " not ", text)
    text = re.sub(r"i'm", "i am ", text)
    text = re.sub(r"\'re", " are ", text)
    text = re.sub(r"\'d", " would ", text)
    text = re.sub(r"\'ll", " will ", text)
    text = re.sub(r"\' +", " ", text)
    text = re.sub(r"\d+", "", text)
    chars = re.escape(string.punctuation)
    text=re.sub(r'['+chars+']',"",text)
    
    text=text.split()
    stops=set(stopwords.words("english"))
    text = [x for x in text if x not in stops]
    
    text = [t for t in text if len(t) > 0]
    # pos tag text
    pos_tags = pos_tag(text)
    # lemmatize text
    text = [WordNetLemmatizer().lemmatize(t[0], get_wordnet_pos(t[1])) for t in pos_tags]
    # remove words with only one letter
    text = [t for t in text if len(t) > 1]
    # join all
    text = " ".join(text)
    return text

In [22]:
data.head(1)

reviewtext Sentiment
0  Nice Marriot       View of my king bed room      good

In [23]:
#applying custom function for text clean up on train data
data['reviewtext'] = data['reviewtext'].map(lambda x: clean_text(x))

In [25]:
data.head(10)

reviewtext  Sentiment
0                    nice marriot view king bed room       good
1  good hotel charge internet access marriott air...       good
2  small adequate room early morning flight catch...       good
3  good average noisy room stay hotel time inthe ...       good
4  ordinary although highly rat reviews pay premi...        bad
5  awesome early flight wow suprise stay property...  excellent
6  good stay spend two night jun hotel close airp...       good
7  great staff stay overnight last week may fly m...  excellent
8  fine choice seatac lobby attractive bit small ...       good
9  great value look nice hotel expensive nice ser...       good

In [28]:
#applying custom function for text clean up on test data
testData['reviewtext'] = testData['reviewtext'].map(lambda x: clean_text(x))

In [29]:
# Print the unique classes and their counts/frequencies
classes = np.unique(data['Sentiment'], return_counts=True) # np.unique returns a tuple with class names and counts
print(classes[0]) #Print the list of unique classes
print(classes[1]) #Print the list of frequencies of the above classes

['bad' 'excellent' 'good']
[1103 1971 3213]


In [30]:
#Target and Predictor 
y=data.drop(columns='reviewtext', axis = 1)
X=data.drop(columns="Sentiment",axis=1)

In [31]:
#Split Train and Test Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
                                    data['reviewtext'], data['Sentiment'], random_state=3422, test_size=0.2)

In [32]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)


(5029,)
(5029,)
(1258,)
(1258,)


# Logistic Regression

In [33]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
#Lets construct TF-idf matrix based on the train documents
tfidf_transformer = TfidfVectorizer(ngram_range=(1,1),stop_words='english',lowercase = True)
X_train_tfidf = tfidf_transformer.fit_transform(X_train)
X_Train_Dense = X_train_tfidf.todense()
X_Train_tf=pd.DataFrame(X_Train_Dense)
X_Train_tf.shape

(5029, 22872)

In [34]:
X_unseen_test_data_tfidf = tfidf_transformer.transform(testData['reviewtext'])
X_unseen_test_dense = X_unseen_test_data_tfidf.todense()
X_unseen_tf=pd.DataFrame(X_unseen_test_dense)
X_unseen_tf.shape

(3468, 22872)

In [35]:
y_train_tfidf = tfidf_transformer.transform(y_train)
y_train_tfidf.shape

(5029, 22872)

In [36]:
# Get the tfidf matrix for test documents
X_val_tfidf = tfidf_transformer.transform(X_test)
X_val_dense = X_val_tfidf.todense()
X_val_tf = pd.DataFrame(X_val_dense)
X_val_tf.shape

(1258, 22872)

In [37]:
X_unseen_tf.shape, X_val_tf.shape

((3468, 22872), (1258, 22872))

In [32]:
from sklearn import linear_model

logreg_train = LogisticRegression(C= 10, tol = 0.01)

lr_clf = logreg_train.fit(X_Train_tf, y_train)

pred_lr_train=lr_clf.predict(X_Train_tf) # predict on train data
pred_lr_val = lr_clf.predict(X_val_tf)

pred_lr_test = lr_clf.predict(X_unseen_tf)

print(pred_lr_test)
print("Train_Confusion matrix:\n", confusion_matrix(y_test,pred_lr_val))
acc2 = accuracy_score(y_test,pred_lr_val)
acc2

C:\Users\CBPLDEV11\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning:

Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.

C:\Users\CBPLDEV11\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning:

Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.



['good' 'bad' 'bad' ... 'bad' 'good' 'excellent']
Train_Confusion matrix:
 [[139   4  62]
 [  7 234 173]
 [ 35 129 475]]


0.6740858505564388

In [33]:
labels = "reviewtext"

In [34]:
testLabelsSenti_5 = pd.DataFrame(pred_lr_test, columns = [labels])

In [102]:
submission_2 = pd.concat([reviewId_Test, testLabelsSenti_5], axis = 1)
submission_2.to_csv("Submission_5.csv", index = False)

In [39]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]}
# clf = GridSearchCV(LogisticRegression(penalty='l2'), param_grid)

clf_cv = GridSearchCV(estimator=LogisticRegression(random_state = 899, tol = 0.001, class_weight='balanced'),
            param_grid=param_grid, verbose=True, cv = 10,n_jobs = -1)

lr_clf = clf_cv.fit(X_Train_tf, y_train)

pred_lr_train=lr_clf.predict(X_Train_tf) # predict on train data
pred_lr_val = lr_clf.predict(X_val_tf)

pred_lr_test_2 = lr_clf.predict(X_unseen_tf)

print(pred_lr_test_2)
print("Train_Confusion matrix:\n", confusion_matrix(y_test,pred_lr_val))
acc2 = accuracy_score(y_test,pred_lr_val)
acc2

Fitting 10 folds for each of 7 candidates, totalling 70 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done  70 out of  70 | elapsed:  1.7min finished
C:\Users\CBPLDEV11\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning:

Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.

C:\Users\CBPLDEV11\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning:

Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.



['good' 'bad' 'bad' ... 'bad' 'bad' 'excellent']
Train_Confusion matrix:
 [[161   3  41]
 [ 15 254 145]
 [ 51 137 451]]


0.6883942766295708

In [36]:
testLabelsSenti_6 = pd.DataFrame(pred_lr_test_2, columns = [labels])
submission_6 = pd.concat([reviewId_Test, testLabelsSenti_6], axis = 1)
submission_6.to_csv("Submission_6.csv", index = False)

# CNN Model

In [42]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [48]:
tokenizer = Tokenizer(num_words=max_num_words) #Tokenizer is used to tokenize text
tokenizer.fit_on_texts(X_train)


x_train = tokenizer.texts_to_sequences(X_train) #'text to sequences converts the text to a list of indices
x_train = pad_sequences(x_train, maxlen=seq_len) #pad_sequences makes every sequence a fixed size list by padding with 0s 

x_val = tokenizer.texts_to_sequences(X_test) #'text to sequences converts the text to a list of indices
x_val = pad_sequences(x_val, maxlen=seq_len) #pad_sequences makes every sequence a fixed size list by padding with 0s 

x_train.shape, x_val.shape

((5029, 200), (1258, 200))

In [49]:
tokenizer_test = Tokenizer(num_words=max_num_words) #Tokenizer is used to tokenize text
tokenizer_test.fit_on_texts(X_train)


x_test = tokenizer_test.texts_to_sequences(testData.reviewtext) #'text to sequences converts the text to a list of indices
x_test = pad_sequences(x_test, maxlen=seq_len) #pad_sequences makes every sequence a fixed size list by padding with 0s 

y_test_2 = tokenizer_test.texts_to_sequences(y_test) #'text to sequences converts the text to a list of indices
y_test_2= pad_sequences(x_test, maxlen=seq_len)

x_test.shape, y_test_2.shape

((3468, 200), (3468, 200))

In [50]:
#checking counts
A=tokenizer.word_counts
sorted_by_value = sorted(A.items(), key=lambda kv: kv[1],reverse=True)
print(sorted_by_value[0:100])
print(len(sorted_by_value))

[('hotel', 11301), ('room', 10745), ('stay', 6526), ('great', 4765), ('would', 3751), ('get', 3359), ('good', 3201), ('location', 3135), ('night', 3023), ('nice', 2842), ('staff', 2836), ('one', 2522), ('time', 2303), ('go', 2299), ('bed', 2252), ('clean', 2220), ('day', 1987), ('place', 1961), ('walk', 1929), ('service', 1857), ('small', 1698), ('also', 1653), ('area', 1610), ('breakfast', 1599), ('well', 1582), ('restaurant', 1581), ('could', 1520), ('like', 1466), ('floor', 1387), ('make', 1386), ('bathroom', 1383), ('price', 1340), ('take', 1326), ('view', 1323), ('desk', 1307), ('street', 1301), ('find', 1291), ('even', 1278), ('friendly', 1260), ('park', 1249), ('really', 1235), ('comfortable', 1230), ('back', 1227), ('two', 1215), ('check', 1203), ('look', 1201), ('front', 1160), ('helpful', 1157), ('book', 1145), ('little', 1122), ('say', 1108), ('use', 1093), ('car', 1076), ('need', 1072), ('city', 1068), ('free', 1065), ('want', 1060), ('pool', 1025), ('square', 1021), ('bloc

In [51]:
#checking counts
A=tokenizer_test.word_counts
sorted_by_value = sorted(A.items(), key=lambda kv: kv[1],reverse=True)
print(sorted_by_value[0:100])
print(len(sorted_by_value))

[('hotel', 11301), ('room', 10745), ('stay', 6526), ('great', 4765), ('would', 3751), ('get', 3359), ('good', 3201), ('location', 3135), ('night', 3023), ('nice', 2842), ('staff', 2836), ('one', 2522), ('time', 2303), ('go', 2299), ('bed', 2252), ('clean', 2220), ('day', 1987), ('place', 1961), ('walk', 1929), ('service', 1857), ('small', 1698), ('also', 1653), ('area', 1610), ('breakfast', 1599), ('well', 1582), ('restaurant', 1581), ('could', 1520), ('like', 1466), ('floor', 1387), ('make', 1386), ('bathroom', 1383), ('price', 1340), ('take', 1326), ('view', 1323), ('desk', 1307), ('street', 1301), ('find', 1291), ('even', 1278), ('friendly', 1260), ('park', 1249), ('really', 1235), ('comfortable', 1230), ('back', 1227), ('two', 1215), ('check', 1203), ('look', 1201), ('front', 1160), ('helpful', 1157), ('book', 1145), ('little', 1122), ('say', 1108), ('use', 1093), ('car', 1076), ('need', 1072), ('city', 1068), ('free', 1065), ('want', 1060), ('pool', 1025), ('square', 1021), ('bloc

In [52]:
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

Found 23138 unique tokens.


In [53]:
word_index = tokenizer_test.word_index
print('Found %s unique tokens.' % len(word_index))

Found 23138 unique tokens.


In [54]:
unique_labels = list(y_train.unique())
print(unique_labels)

['good', 'bad', 'excellent']


In [55]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()                  # converts the character array to numeric array. Assigns levels to unique labels.
le.fit(y_train)
train_labels = le.transform(y_train)
val_labels = le.transform(y_test)

print(le.classes_)
print(np.unique(train_labels, return_counts=True))
print(np.unique(val_labels, return_counts=True))

['bad' 'excellent' 'good']
(array([0, 1, 2]), array([ 898, 1557, 2574], dtype=int64))
(array([0, 1, 2]), array([205, 414, 639], dtype=int64))


In [56]:
from keras.utils import to_categorical

labels_train = to_categorical(np.asarray(train_labels))
labels_val = to_categorical(np.asarray(val_labels))

print('Shape of data tensor:', y.shape)
print('Shape of trian label tensor:', labels_train.shape)
print('Shape of validation label tensor:', labels_val.shape)

Shape of data tensor: (6287, 1)
Shape of trian label tensor: (5029, 3)
Shape of validation label tensor: (1258, 3)


In [57]:
# Basic CNN 1D
from keras.models import Sequential 
from keras.layers import Dense, Input, Flatten, Dropout, BatchNormalization
from keras.layers import Conv1D, MaxPooling1D, GlobalMaxPool1D, Embedding


model = Sequential()
model.add(Embedding(max_num_words,
                    embedding_size,
                    input_length=seq_len
                    ))
model.add(Conv1D(64, 5, activation='relu'))
model.add(Dropout(0.25))

model.add(GlobalMaxPool1D())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(3, activation='softmax'))

In [58]:
from keras.optimizers import Adam
adam = Adam(lr=0.001)

In [59]:
model.compile(loss='categorical_crossentropy', #compiling
              optimizer=adam,
              metrics=['accuracy'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 200, 100)          20000     
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 196, 64)           32064     
_________________________________________________________________
dropout_1 (Dropout)          (None, 196, 64)           0         
_________________________________________________________________
global_max_pooling1d_1 (Glob (None, 64)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               8320      
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 387       
Total para

In [60]:
print(x_val)
# print(labels_val.shape)

[[  0   0   0 ...  34   2 174]
 [  0   0   0 ...  62 163 163]
 [  0   0   0 ...  41 104   3]
 ...
 [  0   0   0 ... 199  85 124]
 [  0   0   0 ... 112  61  25]
 [  0   0   0 ...   0   0   1]]


In [61]:
model.fit(x_train, labels_train,  #Fitting
          batch_size=64,
          epochs=5,
          validation_data=(x_val, labels_val))

Train on 5029 samples, validate on 1258 samples
Epoch 1/5
5029/5029 [==============================] - 14s 3ms/step - loss: 0.9960 - acc: 0.5035 - val_loss: 0.9404 - val_acc: 0.5079
Epoch 2/5
5029/5029 [==============================] - 12s 2ms/step - loss: 0.8293 - acc: 0.5870 - val_loss: 0.7807 - val_acc: 0.6097
Epoch 3/5
5029/5029 [==============================] - 12s 2ms/step - loss: 0.7225 - acc: 0.6606 - val_loss: 0.7463 - val_acc: 0.6320
Epoch 4/5
5029/5029 [==============================] - 12s 2ms/step - loss: 0.6645 - acc: 0.6942 - val_loss: 0.7581 - val_acc: 0.6423
Epoch 5/5
5029/5029 [==============================] - 12s 2ms/step - loss: 0.6159 - acc: 0.7200 - val_loss: 0.7564 - val_acc: 0.6455


In [319]:
model.evaluate(x_val, labels_val)

1258/1258 [==============================] - 3s 2ms/step


[0.9747981503961196, 0.6287758345634267]

In [62]:
test_prob=model.predict(x_val) # Checking test probs
test_prob

array([[0.00655592, 0.4681948 , 0.5252492 ],
       [0.00323995, 0.6587146 , 0.33804545],
       [0.02488112, 0.27571857, 0.69940025],
       ...,
       [0.0042456 , 0.23376922, 0.7619852 ],
       [0.5938396 , 0.09765512, 0.30850527],
       [0.23890847, 0.3465262 , 0.41456532]], dtype=float32)

In [63]:
testUnseen_prob= model.predict(x_test)

In [64]:
testUnseen_prob_classes = model.predict_classes(x_test)

In [65]:
testUnseen_prob

array([[0.13167378, 0.24802943, 0.6202968 ],
       [0.62646455, 0.13454306, 0.2389924 ],
       [0.87972903, 0.03318326, 0.08708771],
       ...,
       [0.21790917, 0.30754802, 0.4745428 ],
       [0.313601  , 0.24600518, 0.44039375],
       [0.11607733, 0.5208936 , 0.36302906]], dtype=float32)

In [66]:
testUnseen_prob_classes

array([2, 0, 0, ..., 2, 2, 1], dtype=int64)

In [67]:
testUnseen_prob_classes = le.inverse_transform(testUnseen_prob_classes)


In [68]:
#body belongs to which clases
test_classes=model.predict_classes(x_val) #predicting test classes
test_classes

array([2, 1, 2, ..., 2, 0, 2], dtype=int64)

In [69]:
testUnseen_prob_classes

array(['good', 'bad', 'bad', ..., 'good', 'good', 'excellent'],
      dtype=object)

In [70]:
test_classes=pd.DataFrame(test_classes)
test_classes.shape

(1258, 1)

In [71]:
test_classes1 = np.argmax(test_prob, axis=1)
print(test_classes1.shape)
from sklearn.metrics import accuracy_score
accuracy_score(test_classes1,np.argmax(labels_val, axis=1))

(1258,)


0.6454689984101749

In [72]:
testclasses_test=model.predict_classes(x_test) #predicting test classes
testclasses_test

array([2, 0, 0, ..., 2, 2, 1], dtype=int64)

In [73]:
test_submission = le.inverse_transform(testclasses_test)

In [74]:
test_submission

array(['good', 'bad', 'bad', ..., 'good', 'good', 'excellent'],
      dtype=object)

In [75]:
labels = "Sentiment"

testLabelsSenti = pd.DataFrame(test_submission, columns = [labels])

In [76]:
submission = pd.concat([reviewId_Test, testLabelsSenti], axis = 1)

In [77]:
submission.to_csv("Submission.csv", index = False)

# LSTM Model

In [78]:
from keras.layers import Dense, SimpleRNN, GRU, LSTM, Embedding


model_lstm = Sequential() # Call Sequential to initialize a network
model_lstm.add(Embedding(input_dim = max_num_words, 
                    input_length = seq_len, 
                    output_dim = embedding_size)) # Add an embedding layer which represents each unique token as a vector
model_lstm.add(LSTM(10, return_sequences=True)) # Add an LSTM layer
model_lstm.add(LSTM(10, return_sequences=False))
model_lstm.add(Dense(3, activation='softmax')) # Add an ouput layer. Since classification, 3 nodes for 3 classes.

In [79]:
model_lstm.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 200, 100)          20000     
_________________________________________________________________
lstm_1 (LSTM)                (None, 200, 10)           4440      
_________________________________________________________________
lstm_2 (LSTM)                (None, 10)                840       
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 33        
Total params: 25,313
Trainable params: 25,313
Non-trainable params: 0
_________________________________________________________________


In [80]:
from keras.optimizers import Adam
adam = Adam(lr=0.001)

In [81]:
model_lstm.compile(optimizer=adam,                  # 'Adam' is a variant of gradient descent technique
              loss='categorical_crossentropy', # categorical_crossentropy for multi-class classification
              metrics=['accuracy'])  

In [82]:
#Fitting the Model
model_lstm.fit(x_train, labels_train,
          batch_size=64,
          epochs=6,
          validation_data=(x_val, labels_val))

Train on 5029 samples, validate on 1258 samples
Epoch 1/6
5029/5029 [==============================] - 18s 4ms/step - loss: 1.0087 - acc: 0.5088 - val_loss: 0.9218 - val_acc: 0.5246
Epoch 2/6
5029/5029 [==============================] - 16s 3ms/step - loss: 0.8566 - acc: 0.5788 - val_loss: 0.8382 - val_acc: 0.6017
Epoch 3/6
5029/5029 [==============================] - 16s 3ms/step - loss: 0.7784 - acc: 0.6365 - val_loss: 0.7984 - val_acc: 0.6129
Epoch 4/6
5029/5029 [==============================] - 15s 3ms/step - loss: 0.7328 - acc: 0.6639 - val_loss: 0.7619 - val_acc: 0.6486
Epoch 5/6
5029/5029 [==============================] - 16s 3ms/step - loss: 0.7037 - acc: 0.6850 - val_loss: 0.7624 - val_acc: 0.6494
Epoch 6/6
5029/5029 [==============================] - 15s 3ms/step - loss: 0.6854 - acc: 0.6946 - val_loss: 0.7670 - val_acc: 0.6423
